# This workflow is updated to use GitHub Actions OIDC for Azure Workload Identity Federation.
# Environment: DEV — the job below is configured to run in that environment so it can access environment-level secrets.
# Make sure you created an Azure AD application with a federated credential for:
#   issuer: https://token.actions.githubusercontent.com
#   subject: repo:mirontoli/lab-github-actions-to-azure:environment:DEV
# and audience: ["api://AzureADTokenExchange"]
# Add these secrets to the DEV environment (not repository secrets): AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_SUBSCRIPTION_ID

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Required permission to mint OIDC tokens for the job
permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: DEV

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


      - name: Login to Azure using OIDC (Workload Identity Federation)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # Note: Do NOT provide a client-secret. The action will use the OIDC token from GitHub.

      - name: Verify Azure login
        run: az account show

      - name: Deploy Azure Resource Group
        run: |
          az deployment sub create \
            --location westeurope \
            --template-file infra/main.bicep

      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
